CLASSMAPPING = "/data/GAFdataset/classmapping.isprs.csv"

RAY_NUM_SAMPLES=300
RAY_TEST_EVERY=2
RAY_EPOCHS=40

HYPERBAND_GRACE_PERIOD=1
HYPERBAND_REDUCTION_FACTOR=2
HYPERBAND_BRACKETS=4

HYPERPARAMETER_PATH = "/data/isprs/ray"

BAVARIAN_CROPS_ROOT="/data/BavarianCrops"
GAFDATASET_ROOT="/data/GAFDataset"
